#!/usr/bin/env python3
"""
Test harness for docs_index_check.py — P-15 Docs Lanes (G6)

≥3 vectors: check passes on repo · INDEX coverage · self-test ran
"""
import pathlib
import subprocess
import unittest

ROOT = pathlib.Path(__file__).resolve().parent.parent
INDEX_PATH = ROOT / "docs" / "INDEX.md"
CHECKER_PATH = ROOT / "scripts" / "docs_index_check.py"

def run_cmd(cmd, cwd=ROOT):
    p = subprocess.run(cmd, shell=True, cwd=str(cwd), capture_output=True, text=True)
    return p

class TestDocsIndex(unittest.TestCase):
    def test_check_passes_on_repo(self):
        """check passes on repo — live run exit 0"""
        p = run_cmd(f"python3 {CHECKER_PATH}")
        self.assertEqual(p.returncode, 0, f"docs_index_check should exit 0 on repo, got {p.stdout} {p.stderr}")
        self.assertIn("0 finding", p.stdout)

    def test_index_coverage(self):
        """INDEX coverage — every docs/*.md listed or whitelisted"""
        self.assertTrue(INDEX_PATH.exists(), "docs/INDEX.md must exist")
        text = INDEX_PATH.read_text(encoding="utf-8")
        docs_files = list((ROOT / "docs").glob("*.md"))
        # At least 36 docs/*.md expected (including INDEX.md itself)
        self.assertGreaterEqual(len(docs_files), 36, f"Expected ≥36 docs/*.md, got {len(docs_files)}")
        # Check that every docs/*.md except INDEX.md is mentioned in INDEX.md
        # Whitelist: INDEX.md itself
        whitelist = {"docs/INDEX.md"}
        missing = []
        for f in docs_files:
            rel = f.relative_to(ROOT).as_posix()
            if rel in whitelist:
                continue
            basename = f.name
            if basename not in text and rel not in text:
                missing.append(rel)
        self.assertEqual(missing, [], f"Orphan docs files not listed in INDEX.md nor whitelisted: {missing}")

        # Check that INDEX lists only existing files — no broken links to non-existing .md
        # We reuse checker logic: if checker passes, this is true, but we also check manually
        p = run_cmd(f"python3 {CHECKER_PATH}")
        self.assertEqual(p.returncode, 0, f"INDEX should list only existing files, checker found: {p.stdout}")

    def test_self_test_ran(self):
        """self-test ran — docs_index_check --self-test ≥4 vectors pass"""
        p = run_cmd(f"python3 {CHECKER_PATH} --self-test")
        self.assertEqual(p.returncode, 0, f"self-test should pass, got {p.stdout} {p.stderr}")
        # Check at least 4 vectors passed
        self.assertIn("passed", p.stdout)
        # Parse "X passed" — ensure ≥4
        import re
        m = re.search(r"(\d+) passed", p.stdout)
        self.assertIsNotNone(m, "self-test output should contain 'X passed'")
        passed = int(m.group(1))
        self.assertGreaterEqual(passed, 4, f"self-test should have ≥4 vectors, got {passed}")

    def test_generated_sublane_honest_label(self):
        """Generated sub-lane honest label — CAPABILITIES and SYSTEM_STATE in Generated with honest label"""
        text = INDEX_PATH.read_text(encoding="utf-8")
        self.assertIn("Generated", text, "INDEX.md should have Generated sub-lane")
        self.assertIn("CAPABILITIES.md", text)
        self.assertIn("SYSTEM_STATE.md", text)
        # Honest label: machine-generated, do not edit manually, generated by render_docs.py
        self.assertIn("machine-generated", text.lower())
        self.assertIn("render_docs.py", text)

if __name__ == "__main__":
    unittest.main()
